/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTree;
import javax.swing.event.TreeSelectionEvent;
import javax.swing.event.TreeSelectionListener;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import pcbEditor.Net;
import pcbPart.Part;
import pcbPrimitives.Pad;

/**
 *
 * @author Albin Hjalmas
 */
public class NetManager extends javax.swing.JFrame {

    // The connection nets
    private ArrayList<Net> nets;
    private ArrayList<Part> parts;
    private Pad selPad; // Currently selected pad.
    private Net selNet; // Currently selected net.
    private Pad selNetPad; // Currently selected pad in the net tree.
    private DefaultMutableTreeNode partTop;
    private DefaultMutableTreeNode netTop;

    /**
     * Creates new form NetManager
     *
     * @param parts the parts to connect.
     * @param nets the nets that define the connections between parts.
     */
    public NetManager(ArrayList<Part> parts, ArrayList<Net> nets) {
        initComponents();
        this.nets = nets;
        this.parts = parts;

        rebuild();

        // Avoid this window to close the whole application
        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                setVisible(false);
            }
        });

        // Add listeners
        partTree.addTreeSelectionListener((TreeSelectionEvent e) -> {
            Object o = ((DefaultMutableTreeNode) e.getPath().getLastPathComponent()).getUserObject();
            if (o instanceof Pad) {
                selPad = (Pad) o;
            } else {
                selPad = null;
            }
        });

        netTree.addTreeSelectionListener((TreeSelectionEvent e) -> {
            Object o = ((DefaultMutableTreeNode) e.getPath().getLastPathComponent()).getUserObject();
            if (o instanceof Net) {
                selNet = (Net) o;
            } else {
                selNet = null;
            }

            if (o instanceof Pad) {
                selNetPad = (Pad) o;
                selNet = ((Pad) o).getNet();
            } else {
                selNetPad = null;
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        netNameTxtField = new javax.swing.JTextField();
        addNetBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        netTree = new javax.swing.JTree();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        partTree = new javax.swing.JTree();
        jPanel3 = new javax.swing.JPanel();
        addToNetBtn = new javax.swing.JButton();
        removeFromNetBtn = new javax.swing.JButton();
        removeNetBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Net Manager");
        setAlwaysOnTop(true);
        setLocation(new java.awt.Point(500, 500));
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Add Net"));

        addNetBtn.setText("Add Net");
        addNetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNetBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(netNameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(addNetBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(netNameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addNetBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jSplitPane1.setDividerLocation(180);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane1.setContinuousLayout(true);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Nets"));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setViewportView(netTree);

        jPanel4.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jSplitPane1.setTopComponent(jPanel4);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Parts"));
        jPanel5.setLayout(new java.awt.BorderLayout());

        jScrollPane2.setViewportView(partTree);

        jPanel5.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jSplitPane1.setRightComponent(jPanel5);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        addToNetBtn.setText("Add To Net");
        addToNetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addToNetBtnActionPerformed(evt);
            }
        });

        removeFromNetBtn.setText("Remove From Net");
        removeFromNetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeFromNetBtnActionPerformed(evt);
            }
        });

        removeNetBtn.setText("Remove Net");
        removeNetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeNetBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(removeFromNetBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addToNetBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(removeNetBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(addToNetBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(removeFromNetBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(removeNetBtn)
                .addGap(0, 327, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 9, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addNetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNetBtnActionPerformed
        String name = netNameTxtField.getText();
        if (name.isEmpty()) {
            JOptionPane.showMessageDialog(this, "You must specify a name!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Check if the name is unique
        int cnt = netTop.getChildCount();
        for (int i = 0; i < cnt; i++) {
            DefaultMutableTreeNode tn = (DefaultMutableTreeNode) netTop.getChildAt(i);
            if (tn.getUserObject().toString().equalsIgnoreCase(name)) {
                JOptionPane.showMessageDialog(this, "The name must be unique!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }
        Net newNet = new Net(name);
        nets.add(newNet);
        netTop.add(new DefaultMutableTreeNode(newNet));
        netTree.setModel(new DefaultTreeModel(netTop));
        revalidate();
    }//GEN-LAST:event_addNetBtnActionPerformed

    private void addToNetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addToNetBtnActionPerformed
        if (selNet == null || selPad == null) {
            JOptionPane.showMessageDialog(this, "You must select a pad and a net!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        selNet.addPad(selPad);
        rebuild();
    }//GEN-LAST:event_addToNetBtnActionPerformed

    private void removeFromNetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeFromNetBtnActionPerformed
        if(selNetPad == null) {
            JOptionPane.showMessageDialog(this, "You must select a pad within a net!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        selNetPad.getNet().removePad(selNetPad);
        rebuild();
    }//GEN-LAST:event_removeFromNetBtnActionPerformed

    private void removeNetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeNetBtnActionPerformed
        if (selNet == null) {
            JOptionPane.showMessageDialog(this, "You must select a net!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Remove all pads from net
        ArrayList<Pad> tmpPads = new ArrayList<>();
        tmpPads.addAll(selNet.getPads());
        for (Pad pad : tmpPads) {
            selNet.removePad(pad);
        }

        nets.remove(selNet);
        rebuild();
    }//GEN-LAST:event_removeNetBtnActionPerformed

    /**
     * Rebuilds the trees.
     */
    private void rebuild() {
        // Create the part tree
        DefaultMutableTreeNode top = new DefaultMutableTreeNode("Parts");
        DefaultMutableTreeNode tmp;
        for (Part part : parts) {
            tmp = new DefaultMutableTreeNode(part);
            for (Pad pad : part.getFootprint().getPads()) {
                if (pad.getNet() == null) {
                    tmp.add(new DefaultMutableTreeNode(pad));
                }
            }
            top.add(tmp);
        }
        partTree.setModel(new DefaultTreeModel(top));
        partTop = top;

        // Create the net tree
        top = new DefaultMutableTreeNode("Nets");
        for (Net net : nets) {
            tmp = new DefaultMutableTreeNode(net);
            for (Pad pad : net.getPads()) {
                // Search for a part that this pad belongs to
                int cnt = tmp.getChildCount();
                boolean padWasAdded = false;
                for (int i = 0; i < cnt; i++) {
                    DefaultMutableTreeNode tn = (DefaultMutableTreeNode) tmp.getChildAt(i);

                    if (pad.getPart() != null && tn.getUserObject().equals(pad.getPart())) {
                        // The pad belongs to this part
                        tn.add(new DefaultMutableTreeNode(pad));
                        padWasAdded = true;
                        break;
                    }
                }

                // If pad did not belong to any part, then add part.
                if (!padWasAdded && pad.getVisible() && pad.getPart() != null) {
                    DefaultMutableTreeNode n = new DefaultMutableTreeNode(pad.getPart());
                    tmp.add(n);
                    n.add(new DefaultMutableTreeNode(pad));
                }
            }
            top.add(tmp);
        }
        netTree.setModel(new DefaultTreeModel(top));
        netTop = top;
        
        // Expand trees
        expandAllNodes(netTree, 0, netTree.getRowCount());
        expandAllNodes(partTree, 0, partTree.getRowCount());
    }

    private void expandAllNodes(JTree tree, int startingIndex, int rowCount) {
        for (int i = startingIndex; i < rowCount; ++i) {
            tree.expandRow(i);
        }

        if (tree.getRowCount() != rowCount) {
            expandAllNodes(tree, rowCount, tree.getRowCount());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addNetBtn;
    private javax.swing.JButton addToNetBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextField netNameTxtField;
    private javax.swing.JTree netTree;
    private javax.swing.JTree partTree;
    private javax.swing.JButton removeFromNetBtn;
    private javax.swing.JButton removeNetBtn;
    // End of variables declaration//GEN-END:variables
}
