package ui;

import java.awt.Dimension;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import pcbPart.Part;
import pcbPrimitives.Pad;

/**
 *
 * @author Albin Hjalmas.
 */
public class PlaceManager extends javax.swing.JDialog {

    private boolean cancelled;
    private Part part;
    private ArrayList<JTextField> txtFields;

    /**
     * Creates new form NewProjectDialog
     */
    public PlaceManager(java.awt.Frame parent, Part part, boolean modal) {
        super(parent, modal);
        initComponents();
        this.part = part;
        txtFields = new ArrayList<>();
        
        // Construct list of pin name text fields
        int i = 1;
        for(Pad pad : part.getFootprint().getPads()) {
            JTextField t = new JTextField();
            t.setMaximumSize(new Dimension(20000, 40));
            t.setBorder(javax.swing.BorderFactory.createTitledBorder("Pin " + i));
            txtFieldPanel.add(t);
            txtFields.add(t);
            i++;
        }
        
        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent evt) {
                setVisible(false);
            }
         });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nameTxtField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtFieldPanel = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(200, 0), new java.awt.Dimension(200, 0), new java.awt.Dimension(200, 32767));
        cancelBtn = new javax.swing.JButton();
        okBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Place Manager");
        setAlwaysOnTop(true);
        setMaximumSize(new java.awt.Dimension(2147483647, 250));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Part Name"));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.X_AXIS));

        nameTxtField.setMaximumSize(new java.awt.Dimension(2147483647, 20));
        jPanel1.add(nameTxtField);

        getContentPane().add(jPanel1);

        txtFieldPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Pin Names"));
        txtFieldPanel.setLayout(new javax.swing.BoxLayout(txtFieldPanel, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(txtFieldPanel);

        getContentPane().add(jScrollPane1);

        jPanel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jPanel4.setMaximumSize(new java.awt.Dimension(32767, 53));
        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));
        jPanel4.add(filler2);

        cancelBtn.setText("Cancel");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });
        jPanel4.add(cancelBtn);

        okBtn.setText("OK");
        okBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okBtnActionPerformed(evt);
            }
        });
        jPanel4.add(okBtn);

        getContentPane().add(jPanel4);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        cancelled = true;
        this.setVisible(false);
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void okBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okBtnActionPerformed
        // Check that no textfield was left empty
        boolean emptyState = false;
        if(nameTxtField.getText().isEmpty()) {
            emptyState = true;
        }
        
        for(JTextField t : txtFields) {
            if(t.getText().isEmpty()) {
                emptyState = true;
            }
        }
        
        if(emptyState) {
            JOptionPane.showMessageDialog(this, "You must specify a name for the"
                    + " part and each of it's pins!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Set the name of the part
        part.setName(nameTxtField.getText());
        
        // Set name of the pins
        ArrayList<Pad> pads = part.getFootprint().getPads();
        int i = 0;
        for(JTextField field : txtFields) {
            pads.get(i).setName(field.getText());
            i++;
        }
        
        cancelled = false;
        
        setVisible(false);
    }//GEN-LAST:event_okBtnActionPerformed

    // Getters

    public boolean wasCancelled() {
        return cancelled;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelBtn;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nameTxtField;
    private javax.swing.JButton okBtn;
    private javax.swing.JPanel txtFieldPanel;
    // End of variables declaration//GEN-END:variables
}
